// import "./src/styles/prism/prism-monokai.css"
// import "prismjs/themes/prism-okaidia.css"
import "prismjs/themes/prism-solarizedlight.css"
import "prismjs/plugins/line-numbers/prism-line-numbers.css"
import "./src/styles/prism/numbering-fix.css"
import "./src/styles/prism/line-highlighting.css"
